### ISSUE TITLE
problems running publish-crates@v1 gh action

### ISSUE THREAD

**Issue by izirku** [katyo/publish-crates#412]
I'm getting this trying to run [my workflow](https://github.com/izirku/gitrel/blob/c3bfcda6d3dc51ad0b09d38d44e142affb958f4b/.github/workflows/publish.yml), nothing gets published to crates.io, am I missing something?:

```
Run katyo/publish-crates@v1
(node:1598) UnhandledPromiseRejectionWarning: TypeError: Input does not meet YAML 1.2 "Core Schema" specification: no-verify
Support boolean input list: `true | True | TRUE | false | False | FALSE`
    at getBooleanInput (/home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/node_modules/@actions/core/lib/core.js:151:1)
    at /home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/lib/main.js:33:1
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/lib/main.js:8:1
    at new Promise (<anonymous>)
    at __webpack_modules__.3[10](https://github.com/izirku/gitrel/runs/5270607683?check_suite_focus=true#step:4:10)9.__awaiter (/home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/lib/main.js:4:1)
    at run (/home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/lib/main.js:23:1)
    at Object.3109 (/home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/lib/main.js:97:1)
    at __nccwpck_require__ (/home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/webpack/bootstrap:21:1)
    at /home/runner/work/_actions/katyo/publish-crates/v1/webpack:/publish-crates/webpack/startup:4:1
(node:[15](https://github.com/izirku/gitrel/runs/5270607683?check_suite_focus=true#step:4:15)98) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1598) [DEP00[18](https://github.com/izirku/gitrel/runs/5270607683?check_suite_focus=true#step:4:18)] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Voxelot** [comment]
Looks like a PR I made (#394) missed adding a default value to the action.yml file. Sorry for the disruption, I've opened another PR (#414) with a fix.

**Comment by izirku** [comment]
@Voxelot , no worries, thank you!
